### ISSUE TITLE
Error trying to use ZonedDate in typescript.

### ISSUE THREAD

**Issue by marcovc** [tranvansang/zoned-date#1]
Hi,

Thanks for your library. I'm getting this error when trying to use it:

```
node_modules/zoned-date/ZonedDate.cjs:545
	Object.defineProperty(ZonedDate.prototype, name, {
                       ^
ReferenceError: ZonedDate is not defined
    at Object.<anonymous> (/node_modules/zoned-date/ZonedDate.cjs:545:24)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/backend/src/csv_importer/time.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

I'm using ts-node, and my node version is v18.16.1. Any clues what can be the issue?

**Comment by tranvansang** [comment]
Will check it soon!

**Comment by marcovc** [comment]
The following fixed it for me:

change `module.exports = class ZonedDate { etc}` into `class ZonedDate { etc}; module.exports = ZonedDate;`

**Comment by tranvansang** [comment]
can you share your tsconfig.json?

**Comment by tranvansang** [comment]
I have reproduced the issue, and looking into it now.

**Comment by tranvansang** [comment]
@marcovc thanks for your investigation. I have followed your fix and uploaded new version to npm.
